config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'evosubmatrice/index'

  get 'evosubmatrice/show'

  resources :sequpairs
  get 'welcome/index'

  get 'welcome/tester'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sequpair.rb
class Sequpair < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/evosubmatrice_controller.rb
class EvosubmatriceController < ApplicationController
  def index
  end

  def show
    @matrixblosum62 = EvoMatrices.getBlosum62('blosum62')
  end
end

app/controllers/sequpairs_controller.rb
class SequpairsController < ApplicationController
  before_action :set_sequpair, only: [:show, :edit, :update, :destroy]

  # GET /sequpairs
  # GET /sequpairs.json
  def index
    @sequpairs = Sequpair.all
  end

  # GET /sequpairs/1
  # GET /sequpairs/1.json
  def show
    @biosum62 = BionasBlosum62.new
    @biosum62.createMatris('blosum62')
    @matrixhtml = @biosum62.getHtmlMatrix(@sequpair)
    # puts "HTML MATRIS: #{@matrixhtml}"
  end

  # GET /sequpairs/new
  def new
    @sequpair = Sequpair.new
  end

  # GET /sequpairs/1/edit
  def edit
  end

  # POST /sequpairs
  # POST /sequpairs.json
  def create
    @sequpair = Sequpair.new(sequpair_params)

    respond_to do |format|
      if @sequpair.save
        format.html {redirect_to @sequpair, notice: 'Sequpair was successfully created.'}
        format.json {render :show, status: :created, location: @sequpair}
      else
        format.html {render :new}
        format.json {render json: @sequpair.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /sequpairs/1
  # PATCH/PUT /sequpairs/1.json
  def update
    respond_to do |format|
      if @sequpair.update(sequpair_params)
        format.html {redirect_to @sequpair, notice: 'Sequpair was successfully updated.'}
        format.json {render :show, status: :ok, location: @sequpair}
      else
        format.html {render :edit}
        format.json {render json: @sequpair.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /sequpairs/1
  # DELETE /sequpairs/1.json
  def destroy
    @sequpair.destroy
    respond_to do |format|
      format.html {redirect_to sequpairs_url, notice: 'Sequpair was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sequpair
    @sequpair = Sequpair.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sequpair_params
    params.require(:sequpair).permit(:seq1, :seq2, :mattype, :result, :gap, :mismatch)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @sequpairmodel = Sequpair.new
    @sequpairmodel.seq1 = "SAMPLE"
    @sequpairmodel.seq2 = "SAMPLE"
    @sequpairmodel.gap = -10
    @sequpairmodel.mismatch = -1
    @sequpairmodel.result = @sequpairmodel.seq1 + ":" + @sequpairmodel.seq2
    @biosum62 = BionasBlosum62.new
    @biosum62.createMatris('blosum62')
    @matrixhtml = @biosum62.getHtmlMatrix(@sequpairmodel)
    puts "HTML MATRIS: #{@matrixhtml}"
  end

  def tester
    @sequence1 = "SAMPLE"
    @sequence2 = "SAMPLE"
    @biosum62 = BionasBlosum62.new
    @biosum62.createMatris('blosum62')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evosubmatrice_helper.rb
module EvosubmatriceHelper
end

app/helpers/sequpairs_helper.rb
module SequpairsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/evosubmatrice/index.html.erb
<h3>Evolutionary Substitution Matrice:BLOSUM62</h3>
<br>
<ul id="menu_wrap">
  <li class="button"><%= link_to "Blosum62", :controller => :evosubmatrice, :action => :show %></li>
  <li class="button"><%= link_to "PAM", :controller => :evosubmatrice, :action => :show, :remote => true, disabled: true %></li>
</ul>

app/views/evosubmatrice/show.html.erb
<h3>Evolutionary Substitution Matrice:BLOSUM62</h3>
<br>

<table id="matrix" style="float: left; table-layout: auto">
  <% @matrixblosum62.each do |r| %>
    <tr>
      <% r.each do |c| %>
        <td><%= c.to_s %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/layouts/_application_header.html.erb
<ul id="menu_wrap" class="White">
  <li class="button"><%= link_to "Welcome", root_path %></li>
  <li class="button"><%= link_to "Aligments", :controller => :sequpairs, :action => :index %></li>
  <li class="button"><%= link_to "EvoSubMatrice", :controller => :evosubmatrice, :action => :index %></li>
  <li class="search"><a href="#"></a><input type="text" placeHolder="Search..."/></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <meta name="description" content="">
  <meta name="author" content="">
  <!--- -->
  <title>Seq</title>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<body class="skin-blue">

<%= render "layouts/application_header" %>

<div class="wrapper row-offcanvas row-offcanvas-left">
  <aside class="left-side sidebar-offcanvas">
    <%= render "layouts/application_sidebar" %>
  </aside>
  <aside class="right-side">
    <%= yield(:content_header) %>
    <div id="menu_wrap" style="color: #B00100">
      <%= yield %>
    </div>
  </aside>
</div>
<div class="spinner no-print hidden">
  <!--<img src="/img/ajax-loader.gif" alt="">-->
</div>

<%= render "layouts/application_footer" %>

</body>

</body>
</html>

app/views/sequpairs/_form.html.erb
<%= form_with(model: sequpair, local: true) do |form| %>
  <% if sequpair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sequpair.errors.count, "error") %> prohibited this sequpair from being saved:</h2>

      <ul>
        <% sequpair.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seq1 %>
    <%= form.text_area :seq1, id: :sequpair_seq1, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :seq2 %>
    <%= form.text_area :seq2, id: :sequpair_seq2 %>
  </div>

  <div class="field">
    <%= form.label :mattype %>
    <%= form.select :mattype, options_for_select(["BLOSUM62", "PAM"]) %>
  </div>

  <div class="field">
    <%# form.label :result %>
    <%= form.hidden_field :result, id: :sequpair_result %>
  </div>

  <div class="field">
    <%= form.label :gap %>
    <%= form.number_field :gap, id: :sequpair_gap, value: -10 %>
  </div>

  <div class="field">
    <%= form.label :mismatch %>
    <%= form.number_field :mismatch, id: :sequpair_mismatch, value: -1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sequpairs/edit.html.erb
<h3>Editing Sequpair</h3>

<%= render 'form', sequpair: @sequpair %>

<%= link_to 'Show', @sequpair %> |
<%= link_to 'Back', sequpairs_path %>

app/views/sequpairs/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Sequpairs</h3>

<table>
  <thead>
    <tr>
      <th>Seq1</th>
      <th>Seq2</th>
      <th>Mattype</th>
      <th>Result</th>
      <th>Gap</th>
      <th>Mismatch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sequpairs.each do |sequpair| %>
      <tr>
        <td><%= sequpair.seq1 %></td>
        <td><%= sequpair.seq2 %></td>
        <td><%= sequpair.mattype %></td>
        <td><%= sequpair.result %></td>
        <td><%= sequpair.gap %></td>
        <td><%= sequpair.mismatch %></td>
        <td><%= link_to 'Show', sequpair %></td>
        <td><%= link_to 'Edit', edit_sequpair_path(sequpair) %></td>
        <td><%= link_to 'Destroy', sequpair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sequpair', new_sequpair_path %>

app/views/sequpairs/new.html.erb
<h3>New Sequpair</h3>

<%= render 'form', sequpair: @sequpair %>

<%= link_to 'Back', sequpairs_path %>

app/views/sequpairs/show.html.erb
<h3><%= @sequpair.mattype %></h3>
<br>
<div>
  <div class="divSol">
    <div>
      <table id="solTable" style="empty-cells: show; width: max-content; float: right;">
        <tr>
          <th colspan="2">&nbsp;</th>
        </tr>
        <tr>
          <th colspan="2">&nbsp;</th>
        </tr>
        <% @sequpair.seq1.each_char do |c| %>
          <tr>
            <td><strong><%= c %></strong></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="divOrta">
    <table id="matrix" style="float: left; table-layout: fixed;margin: 0px;overflow: hidden">
      <tr>
        <th>&nbsp;</th>
        <% @sequpair.seq2.each_char do |c| %>
          <th><%= c %></th>
        <% end %>
      </tr>
      <tbody id="tmatrisvalue">
      <% @matrixhtml.each do |r| %>
        <tr>
          <% r.each do |c| %>
            <td style="background-color: <%= 'yellow' if c.on_path != 0 %>">
              <%= c.value %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="divSol">
    <div class="divSag" style="height: 100vh;">
      <p>
        <%= @sequpair.mattype %>
      </p>
      <strong>Seq1:</strong>
      <p>
        <%= @sequpair.seq1 %>
      </p>
      <strong>Seq2:</strong>
      <p>
        <%= @sequpair.seq2 %>
      </p>
      <strong>Result:</strong>
      <p style="text-align: right">
        <%= @sequpair.result.split(':')[0] %>
        <br>
        <%= @sequpair.result.split(':')[1] %>
      </p>
      <br>
      <input type="button" value="Cell View" onclick="showCellType()" style="cursor:default ">
      <br>
      <br>
      <div>
        <%= link_to 'Edit', edit_sequpair_path(@sequpair) %> |
        <%= link_to 'Back', sequpairs_path %>
      </div>
    </div>
  </div>
  <div class="divSol">
    <div>
      <table id="solTable2" style="empty-cells: show; width: max-content; float: right;">
        <tr>
          <th colspan="2">&nbsp;</th>
        </tr>
        <tr>
          <th colspan="2">&nbsp;</th>
        </tr>
        <% @sequpair.seq1.each_char do |c| %>
          <tr>
            <td><strong><%= c %></strong></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="divOrta">
    <table id="matrix2" style="float: left; table-layout: fixed;margin: 0px;overflow: hidden">
      <tr>
        <th>&nbsp;</th>
        <% @sequpair.seq2.each_char do |c| %>
          <th><%= c %></th>
        <% end %>
      </tr>
      <tbody id="tmatrisvalue2">
      <% @matrixhtml.each do |r| %>
        <tr>
          <% r.each do |c| %>
            <td style="background-color: <%= 'yellow' if c.on_path != 0 %>">
              <%= c.cell_type %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>
<br>
<br>
<br>

<script>
    function showBestPath() {
        var table = document.getElementById('matrix');
        for (var r = 0, n = table.rows.length; r < n; r++) {
            for (var c = 0, m = table.rows[r].cells.length; c < m; c++) {
                if (r > 0 && r == c) {
                    //alert(table.rows[r].cells[c].innerHTML);
                    table.rows[r].cells[c].bgColor = "Orange";
                }
            }
        }
    }

    function showCellType() {
        if (document.getElementById('tmatriscelltype').style.display == 'none') {
            show('tmatriscelltype')
            hide('tmatrisvalue')
        } else {
            hide('tmatriscelltype')
            show('tmatrisvalue')
        }
    }

    function hide(id) {
        var divObject = document.getElementById(id);
        divObject.style.display = "none";
    }

    function show(id) {
        var divObject = document.getElementById(id);
        divObject.style.display = "block";
    }
</script>

app/views/welcome/index.html.erb
<h3>Welcome to BioInformatics World!</h3>
<br>
<div class="divSol">
  <div>
    <table id="solTable" style="empty-cells: show; width: max-content; float: right;">
      <tr>
        <th colspan="2">&nbsp;</th>
      </tr>
      <tr>
        <th colspan="2">&nbsp;</th>
      </tr>
      <% @sequpairmodel.seq1.each_char do |c| %>
        <tr>
          <td><%= c %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="divOrta">
  <table id="matrix" style="float: left; table-layout: fixed;margin: 0px">
    <tr>
      <th>&nbsp;</th>
      <% @sequpairmodel.seq2.each_char do |c| %>
        <th><%= c %></th>
      <% end %>
    </tr>
    <% @matrixhtml.each do |r| %>
      <tr>
        <% r.each do |c| %>
          <td>
            <%= c.value %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>
</div>